<?php $currentId = (int) ($_SESSION['user']['id'] ?? 0); $matriculeSession = $_SESSION['user']['matricule'] ?? 'Utilisateur'; $nomSession = trim($_SESSION['user']['nom_utilisateur'] ?? '') ?: $matriculeSession; $profilSession = $_SESSION['user']['profil'] ?? ''; ?>
<!DOCTYPE html><html lang="fr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Utilisateurs - <?= APP_NAME ?></title><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Outfit:wght@600;700&display=swap" rel="stylesheet"><link href="<?= BASE_URL ?>/assets/css/dashboard.css" rel="stylesheet"><link href="<?= BASE_URL ?>/assets/css/users.css" rel="stylesheet"><link href="<?= BASE_URL ?>/assets/css/profile.css" rel="stylesheet"><link href="<?= BASE_URL ?>/assets/css/theme.css" rel="stylesheet"><script src="<?= BASE_URL ?>/assets/js/theme-mode.js"></script></head><body>
<div class="dashboard-shell"><div class="mobile-overlay" id="mobile-overlay" onclick="toggleSidebar()"></div><aside class="dashboard-sidebar" id="dashboard-sidebar">
<a class="brand" href="<?= BASE_URL ?>/dashboard"><span class="brand-icon"><i class="bi bi-truck"></i></span><span><strong>MWIRA Trans</strong><small>Gestion de transport</small></span></a>
<nav class="dashboard-nav"><span class="nav-heading">Vue générale</span><a href="<?= BASE_URL ?>/dashboard"><i class="bi bi-grid-1x2"></i> Tableau de bord</a><span class="nav-heading">Exploitation</span><a href="<?= BASE_URL ?>/vehicules"><i class="bi bi-truck"></i> Véhicules</a><a href="<?= BASE_URL ?>/travailleurs"><i class="bi bi-people"></i> Travailleurs</a><a href="<?= BASE_URL ?>/affectations"><i class="bi bi-arrow-left-right"></i> Affectations</a><span class="nav-heading">Finances</span><a href="<?= BASE_URL ?>/recettes"><i class="bi bi-graph-up-arrow"></i> Recettes</a><a href="<?= BASE_URL ?>/depenses"><i class="bi bi-wallet2"></i> Dépenses</a><a href="<?= BASE_URL ?>/caisse"><i class="bi bi-bank"></i> Caisse</a><span class="nav-heading">Administration</span><a class="active" href="<?= BASE_URL ?>/utilisateurs"><i class="bi bi-person-gear"></i> Utilisateurs</a><a href="<?= BASE_URL ?>/audit"><i class="bi bi-journal-text"></i> Audit</a></nav>
<div class="sidebar-user"><span class="avatar"><?php if ($profilSession): ?><img src="<?= BASE_URL . '/' . htmlspecialchars($profilSession) ?>" alt="Profil"><?php else: ?><?= htmlspecialchars(strtoupper(substr($nomSession,0,2))) ?><?php endif; ?></span><span class="user-copy"><strong><?= htmlspecialchars($nomSession) ?></strong><small><?= htmlspecialchars($matriculeSession) ?></small></span><a class="logout" href="<?= BASE_URL ?>/logout"><i class="bi bi-box-arrow-right"></i></a></div></aside>
<main class="dashboard-main"><header class="dashboard-topbar"><button class="menu-button" onclick="toggleSidebar()"><i class="bi bi-list"></i></button><div><h1>Gestion des utilisateurs</h1><p>Comptes et niveaux d’accès</p></div><div class="topbar-date"><i class="bi bi-shield-check"></i> Administration</div></header>
<div class="users-content"><div class="breadcrumbs"><a href="<?= BASE_URL ?>/dashboard">Tableau de bord</a><i class="bi bi-chevron-right"></i><span>Utilisateurs</span></div>
<section class="users-heading"><div><h2>Utilisateurs</h2><p>Gérez les comptes autorisés à accéder à l’application.</p></div><button class="add-button" onclick="openUserModal()"><i class="bi bi-plus-lg"></i> Ajouter un utilisateur</button></section>
<div class="view-tabs"><button class="active" data-view="users"><i class="bi bi-people"></i> Utilisateurs <span><?= count($utilisateurs) ?></span></button><button data-view="roles"><i class="bi bi-shield-lock"></i> Rôles <span>3</span></button></div>
<section class="users-toolbar"><label class="search-field"><i class="bi bi-search"></i><input id="user-search" type="search" placeholder="Rechercher un matricule ou un rôle…" oninput="filterRows()"></label><span id="result-count"><?= count($utilisateurs) ?> utilisateur(s)</span></section>
<section class="users-table-card view-panel" id="users-view"><div class="users-table-scroll"><table><thead><tr><th>Utilisateur</th><th>Rôle</th><th>Dernière connexion</th><th>Création</th><th>Statut</th><th></th></tr></thead><tbody id="users-body">
<?php if (!$utilisateurs): ?><tr><td colspan="6" class="users-empty"><i class="bi bi-people"></i><strong>Aucun utilisateur</strong><span>Ajoutez le premier compte pour commencer.</span></td></tr><?php endif; ?>
<?php foreach ($utilisateurs as $user): $displayName = trim($user['nom_utilisateur']) ?: $user['matricule']; $encoded = htmlspecialchars(json_encode(['id'=>(int)$user['id'],'nom_utilisateur'=>$displayName,'role'=>$user['role'],'profil'=>$user['profil']]), ENT_QUOTES, 'UTF-8'); ?><tr data-search="<?= htmlspecialchars(strtolower($displayName.' '.$user['matricule'].' '.$user['role'])) ?>"><td><div class="identity"><span><?php if ($user['profil']): ?><img src="<?= BASE_URL . '/' . htmlspecialchars($user['profil']) ?>" alt="Profil"><?php else: ?><?= htmlspecialchars(strtoupper(substr($displayName,0,2))) ?><?php endif; ?></span><div><strong><?= htmlspecialchars($displayName) ?></strong><small><?= htmlspecialchars($user['matricule']) ?></small></div></div></td><td><span class="role-badge role-<?= strtolower($user['role']) ?>"><?= htmlspecialchars($user['role']) ?></span></td><td><?= $user['derniere_connexion'] ? date('d/m/Y H:i', strtotime($user['derniere_connexion'])) : '<span class="muted">Jamais</span>' ?></td><td><?= date('d/m/Y', strtotime($user['created_at'])) ?></td><td><span class="active-badge"><i></i> Actif</span></td><td><div class="row-actions"><button onclick="openUserModal(<?= $encoded ?>)" title="Modifier"><i class="bi bi-pencil"></i></button><?php if ((int)$user['id'] !== $currentId): ?><button class="danger" onclick="openDeleteModal(<?= (int)$user['id'] ?>,'<?= htmlspecialchars($displayName, ENT_QUOTES) ?>')" title="Désactiver"><i class="bi bi-trash3"></i></button><?php endif; ?></div></td></tr><?php endforeach; ?>
</tbody></table></div></section>
<section class="users-table-card view-panel hidden" id="roles-view"><div class="users-table-scroll"><table><thead><tr><th>Rôle</th><th>Description</th><th>Utilisateurs</th></tr></thead><tbody><?php foreach (['ADMIN'=>'Accès complet et administration','CEO'=>'Consultation stratégique et rapports','COMPTABLE'=>'Gestion des opérations financières'] as $code=>$description): $count=count(array_filter($utilisateurs,fn($u)=>$u['role']===$code)); ?><tr data-search="<?= strtolower($code.' '.$description) ?>"><td><span class="role-badge role-<?= strtolower($code) ?>"><?= $code ?></span></td><td><?= $description ?></td><td><strong><?= $count ?></strong> utilisateur(s)</td></tr><?php endforeach; ?></tbody></table></div></section>
</div><footer class="dashboard-footer">© <?= date('Y') ?> MWIRA Trans <span>Gestion des utilisateurs</span></footer></main></div>
<?php if ($message): ?><div class="users-toast <?= $messageType === 'error' ? 'error' : '' ?>"><i class="bi bi-<?= $messageType === 'error' ? 'exclamation-circle' : 'check-circle' ?>"></i><?= htmlspecialchars($message) ?></div><?php endif; ?>
<div class="users-modal-overlay" id="user-modal"><div class="users-modal"><div class="modal-title"><div><h3 id="user-modal-title">Ajouter un utilisateur</h3><p id="user-modal-subtitle">Créer un nouveau compte d’accès</p></div><button onclick="closeModal('user-modal')">&times;</button></div><form method="POST" enctype="multipart/form-data" action="<?= BASE_URL ?>/utilisateurs"><input type="hidden" name="action" id="user-action" value="create"><input type="hidden" name="id" id="user-id"><label class="profile-upload"><span class="profile-preview" id="profile-preview"><i class="bi bi-camera"></i></span><span>Photo de profil<small>JPG, PNG ou WEBP · 2 Mo maximum</small></span><input type="file" name="profil" id="user-profile" accept="image/jpeg,image/png,image/webp" onchange="previewProfile(this)"></label><label>Nom de l’utilisateur<input name="nom_utilisateur" id="user-name" required maxlength="100" placeholder="Nom complet"></label><label>Rôle<select name="role" id="user-role" required><option value="ADMIN">Administrateur</option><option value="CEO">CEO</option><option value="COMPTABLE">Comptable</option></select><small>Le matricule sera généré automatiquement selon le rôle et l’année.</small></label><label>Mot de passe<input type="password" name="mot_de_passe" id="user-password" minlength="4" placeholder="Minimum 4 caractères"><small id="password-hint">Obligatoire pour un nouveau compte (4 caractères minimum)</small></label><div class="modal-buttons"><button type="button" class="cancel" onclick="closeModal('user-modal')">Annuler</button><button type="submit" class="save"><i class="bi bi-check-lg"></i> Enregistrer</button></div></form></div></div>
<div class="users-modal-overlay" id="delete-modal"><div class="users-modal confirm-modal"><span class="warning-icon"><i class="bi bi-exclamation-triangle"></i></span><h3>Désactiver cet utilisateur ?</h3><p>Le compte <strong id="delete-name"></strong> ne pourra plus se connecter.</p><form method="POST" action="<?= BASE_URL ?>/utilisateurs"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" id="delete-id"><div class="modal-buttons"><button type="button" class="cancel" onclick="closeModal('delete-modal')">Annuler</button><button class="delete-confirm" type="submit">Désactiver</button></div></form></div></div>
<script>
let activeView='users';document.querySelectorAll('.view-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeView=b.dataset.view;document.getElementById('users-view').classList.toggle('hidden',activeView!=='users');document.getElementById('roles-view').classList.toggle('hidden',activeView!=='roles');filterRows()});
function filterRows(){const q=document.getElementById('user-search').value.toLowerCase().trim();let n=0;document.querySelectorAll('#'+activeView+'-view tbody tr[data-search]').forEach(r=>{const show=!q||r.dataset.search.includes(q);r.style.display=show?'':'none';if(show)n++});document.getElementById('result-count').textContent=n+' résultat(s)'}
function openUserModal(user=null){document.getElementById('user-action').value=user?'update':'create';document.getElementById('user-id').value=user?.id||'';document.getElementById('user-name').value=user?.nom_utilisateur||'';document.getElementById('user-role').value=user?.role||'ADMIN';document.getElementById('user-password').value='';document.getElementById('user-profile').value='';document.getElementById('user-password').required=!user;document.getElementById('user-modal-title').textContent=user?'Modifier l’utilisateur':'Ajouter un utilisateur';document.getElementById('password-hint').textContent=user?'Laissez vide pour conserver le mot de passe (4 caractères minimum si modifié)':'Obligatoire pour un nouveau compte (4 caractères minimum)';document.getElementById('profile-preview').innerHTML=user?.profil?`<img src="<?= BASE_URL ?>/${user.profil}" alt="Profil">`:'<i class="bi bi-camera"></i>';openModal('user-modal')}
function previewProfile(input){if(!input.files[0])return;const reader=new FileReader();reader.onload=e=>document.getElementById('profile-preview').innerHTML=`<img src="${e.target.result}" alt="Aperçu">`;reader.readAsDataURL(input.files[0])}
function openDeleteModal(id,name){document.getElementById('delete-id').value=id;document.getElementById('delete-name').textContent=name;openModal('delete-modal')}function openModal(id){document.getElementById(id).classList.add('show')}function closeModal(id){document.getElementById(id).classList.remove('show')}function toggleSidebar(){document.getElementById('dashboard-sidebar').classList.toggle('open');document.getElementById('mobile-overlay').classList.toggle('show')}setTimeout(()=>document.querySelector('.users-toast')?.remove(),4000);
</script></body></html>
