<?php
$matricule = $_SESSION['user']['matricule'] ?? 'Utilisateur'; $nom = trim($_SESSION['user']['nom_utilisateur'] ?? '') ?: $matricule; $profil = $_SESSION['user']['profil'] ?? ''; $role = $_SESSION['user']['role'] ?? '';
$counts = ['ACTIF'=>0,'EN_MAINTENANCE'=>0,'HORS_SERVICE'=>0,'VENDU'=>0]; foreach ($vehicules as $v) if (isset($counts[$v['statut']])) $counts[$v['statut']]++;
$statusLabels = ['ACTIF'=>'Actif','EN_MAINTENANCE'=>'En maintenance','HORS_SERVICE'=>'Hors service','VENDU'=>'Vendu'];
?>
<!DOCTYPE html><html lang="fr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Véhicules - <?= APP_NAME ?></title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Outfit:wght@600;700&display=swap" rel="stylesheet"><link href="<?= BASE_URL ?>/assets/css/dashboard.css" rel="stylesheet"><link href="<?= BASE_URL ?>/assets/css/users.css" rel="stylesheet"><link href="<?= BASE_URL ?>/assets/css/profile.css" rel="stylesheet"><link href="<?= BASE_URL ?>/assets/css/vehicles.css" rel="stylesheet"><link href="<?= BASE_URL ?>/assets/css/theme.css" rel="stylesheet"><script src="<?= BASE_URL ?>/assets/js/theme-mode.js"></script></head><body>
<div class="dashboard-shell"><div class="mobile-overlay" id="mobile-overlay" onclick="toggleSidebar()"></div><aside class="dashboard-sidebar" id="dashboard-sidebar"><a class="brand" href="<?= BASE_URL ?>/dashboard"><span class="brand-icon"><i class="bi bi-truck"></i></span><span><strong>MWIRA Trans</strong><small>Gestion de transport</small></span></a>
<nav class="dashboard-nav"><span class="nav-heading">Vue générale</span><a href="<?= BASE_URL ?>/dashboard"><i class="bi bi-grid-1x2"></i> Tableau de bord</a><span class="nav-heading">Exploitation</span><a class="active" href="<?= BASE_URL ?>/vehicules"><i class="bi bi-truck"></i> Véhicules</a><a href="<?= BASE_URL ?>/travailleurs"><i class="bi bi-people"></i> Travailleurs</a><a href="<?= BASE_URL ?>/affectations"><i class="bi bi-arrow-left-right"></i> Affectations</a><span class="nav-heading">Finances</span><a href="<?= BASE_URL ?>/recettes"><i class="bi bi-graph-up-arrow"></i> Recettes</a><a href="<?= BASE_URL ?>/depenses"><i class="bi bi-wallet2"></i> Dépenses</a><a href="<?= BASE_URL ?>/caisse"><i class="bi bi-bank"></i> Caisse</a><a href="<?= BASE_URL ?>/rapports"><i class="bi bi-bar-chart"></i> Rapports</a><?php if ($role==='ADMIN'): ?><span class="nav-heading">Administration</span><a href="<?= BASE_URL ?>/utilisateurs"><i class="bi bi-person-gear"></i> Utilisateurs</a><a href="<?= BASE_URL ?>/audit"><i class="bi bi-journal-text"></i> Audit</a><?php endif; ?></nav>
<div class="sidebar-user"><span class="avatar"><?php if($profil):?><img src="<?= BASE_URL.'/'.htmlspecialchars($profil) ?>" alt="Profil"><?php else: ?><?= htmlspecialchars(strtoupper(substr($nom,0,2))) ?><?php endif;?></span><span class="user-copy"><strong><?= htmlspecialchars($nom) ?></strong><small><?= htmlspecialchars($matricule) ?></small></span><a class="logout" href="<?= BASE_URL ?>/logout"><i class="bi bi-box-arrow-right"></i></a></div></aside>
<main class="dashboard-main"><header class="dashboard-topbar"><button class="menu-button" onclick="toggleSidebar()"><i class="bi bi-list"></i></button><div><h1>Gestion des véhicules</h1><p>Flotte et disponibilité opérationnelle</p></div><div class="topbar-date"><i class="bi bi-truck"></i> <?= count($vehicules) ?> véhicule(s)</div></header>
<div class="users-content"><div class="breadcrumbs"><a href="<?= BASE_URL ?>/dashboard">Tableau de bord</a><i class="bi bi-chevron-right"></i><span>Véhicules</span></div>
<section class="users-heading"><div><h2>Parc automobile</h2><p>Ajoutez et suivez tous les véhicules de votre flotte.</p></div><button class="add-button" onclick="openVehicleModal()"><i class="bi bi-plus-lg"></i> Ajouter un véhicule</button></section>
<section class="fleet-stats"><article><i class="bi bi-truck"></i><span><strong><?= count($vehicules) ?></strong><small>Total</small></span></article><article><i class="bi bi-check-circle"></i><span><strong><?= $counts['ACTIF'] ?></strong><small>Actifs</small></span></article><article><i class="bi bi-tools"></i><span><strong><?= $counts['EN_MAINTENANCE'] ?></strong><small>En maintenance</small></span></article><article><i class="bi bi-exclamation-circle"></i><span><strong><?= $counts['HORS_SERVICE'] ?></strong><small>Hors service</small></span></article></section>
<section class="users-toolbar vehicle-toolbar"><label class="search-field"><i class="bi bi-search"></i><input id="vehicle-search" type="search" placeholder="Immatriculation, marque, modèle…" oninput="filterVehicles()"></label><select id="status-filter" onchange="filterVehicles()"><option value="">Tous les statuts</option><?php foreach($statusLabels as $value=>$label):?><option value="<?= $value ?>"><?= $label ?></option><?php endforeach;?></select><span id="vehicle-count"><?= count($vehicules) ?> véhicule(s)</span></section>
<section class="users-table-card"><div class="users-table-scroll"><table class="vehicles-table"><thead><tr><th>Véhicule</th><th>Identification</th><th>Caractéristiques</th><th>Kilométrage</th><th>Statut</th><th></th></tr></thead><tbody id="vehicles-body">
<?php if(!$vehicules):?><tr><td colspan="6" class="users-empty"><i class="bi bi-truck"></i><strong>Aucun véhicule</strong><span>Ajoutez le premier véhicule de la flotte.</span></td></tr><?php endif;?>
<?php foreach($vehicules as $v): $json=htmlspecialchars(json_encode($v),ENT_QUOTES,'UTF-8'); $search=strtolower(implode(' ',[$v['immatriculation'],$v['marque'],$v['modele'],$v['numero_chassis'],$v['type_vehicule']]));?><tr data-search="<?= htmlspecialchars($search) ?>" data-status="<?= htmlspecialchars($v['statut']) ?>"><td><div class="vehicle-cell"><span><i class="bi bi-truck-front"></i></span><div><strong><?= htmlspecialchars($v['marque'] ?: 'Sans marque') ?> <?= htmlspecialchars($v['modele'] ?: '') ?></strong><small><?= htmlspecialchars($v['type_vehicule'] ?: 'Type non défini') ?></small></div></div></td><td><strong class="registration"><?= htmlspecialchars($v['immatriculation']) ?></strong><small class="block-muted"><?= htmlspecialchars($v['numero_chassis'] ?: 'Châssis non renseigné') ?></small></td><td><?= $v['annee'] ? (int)$v['annee'] : '—' ?> · <?= htmlspecialchars($v['couleur'] ?: 'Couleur inconnue') ?><small class="block-muted"><?= $v['capacite_passagers'] ? (int)$v['capacite_passagers'].' passager(s)' : '' ?></small></td><td><?= number_format((float)$v['kilometrage_initial'],0,',',' ') ?> km</td><td><span class="vehicle-status status-<?= strtolower($v['statut']) ?>"><?= $statusLabels[$v['statut']] ?? $v['statut'] ?></span></td><td><div class="row-actions"><button onclick="openVehicleModal(<?= $json ?>)" title="Modifier"><i class="bi bi-pencil"></i></button><button class="danger" onclick="openDeleteVehicle(<?= (int)$v['id'] ?>,'<?= htmlspecialchars($v['immatriculation'],ENT_QUOTES) ?>')" title="Supprimer"><i class="bi bi-trash3"></i></button></div></td></tr><?php endforeach;?></tbody></table></div></section>
</div><footer class="dashboard-footer">© <?= date('Y') ?> MWIRA Trans <span>Gestion de la flotte</span></footer></main></div>
<?php if($message):?><div class="users-toast <?= $messageType==='error'?'error':'' ?>"><i class="bi bi-<?= $messageType==='error'?'exclamation-circle':'check-circle' ?>"></i><?= htmlspecialchars($message) ?></div><?php endif;?>
<div class="users-modal-overlay" id="vehicle-modal"><div class="users-modal vehicle-modal"><div class="modal-title"><div><h3 id="vehicle-modal-title">Ajouter un véhicule</h3><p>Informations techniques et administratives</p></div><button onclick="closeModal('vehicle-modal')">&times;</button></div><form method="POST" action="<?= BASE_URL ?>/vehicules"><input type="hidden" name="action" id="vehicle-action" value="create"><input type="hidden" name="id" id="vehicle-id"><div class="form-grid"><label>Immatriculation *<input name="immatriculation" id="immatriculation" required maxlength="50" placeholder="AB 123 CD"></label><label>Numéro de châssis<input name="numero_chassis" id="numero_chassis" maxlength="100"></label><label>Marque<input name="marque" id="marque" maxlength="100" placeholder="Mercedes"></label><label>Modèle<input name="modele" id="modele" maxlength="100"></label><label>Année<input type="number" name="annee" id="annee" min="1900" max="<?= date('Y')+1 ?>"></label><label>Couleur<input name="couleur" id="couleur" maxlength="50"></label><label>Type de véhicule<input name="type_vehicule" id="type_vehicule" maxlength="100" placeholder="Camion benne"></label><label>Capacité passagers<input type="number" name="capacite_passagers" id="capacite_passagers" min="0"></label><label>Kilométrage initial<input type="number" name="kilometrage_initial" id="kilometrage_initial" min="0" step="0.01" value="0"></label><label>Date d’acquisition<input type="date" name="date_acquisition" id="date_acquisition"></label><label class="full-field">Statut<select name="statut" id="statut"><?php foreach($statusLabels as $value=>$label):?><option value="<?= $value ?>"><?= $label ?></option><?php endforeach;?></select></label></div><div class="modal-buttons"><button type="button" class="cancel" onclick="closeModal('vehicle-modal')">Annuler</button><button type="submit" class="save"><i class="bi bi-check-lg"></i> Enregistrer</button></div></form></div></div>
<div class="users-modal-overlay" id="delete-vehicle-modal"><div class="users-modal confirm-modal"><span class="warning-icon"><i class="bi bi-exclamation-triangle"></i></span><h3>Supprimer ce véhicule ?</h3><p>Le véhicule <strong id="delete-vehicle-name"></strong> sera retiré de la liste.</p><form method="POST" action="<?= BASE_URL ?>/vehicules"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" id="delete-vehicle-id"><div class="modal-buttons"><button type="button" class="cancel" onclick="closeModal('delete-vehicle-modal')">Annuler</button><button type="submit" class="delete-confirm">Supprimer</button></div></form></div></div>
<script>
function openVehicleModal(v=null){const fields=['immatriculation','numero_chassis','marque','modele','annee','couleur','type_vehicule','capacite_passagers','kilometrage_initial','date_acquisition','statut'];document.getElementById('vehicle-action').value=v?'update':'create';document.getElementById('vehicle-id').value=v?.id||'';fields.forEach(f=>document.getElementById(f).value=v?.[f]??(f==='kilometrage_initial'?0:f==='statut'?'ACTIF':''));document.getElementById('vehicle-modal-title').textContent=v?'Modifier le véhicule':'Ajouter un véhicule';openModal('vehicle-modal')}
function filterVehicles(){const q=document.getElementById('vehicle-search').value.toLowerCase().trim(),s=document.getElementById('status-filter').value;let n=0;document.querySelectorAll('#vehicles-body tr[data-search]').forEach(r=>{const show=(!q||r.dataset.search.includes(q))&&(!s||r.dataset.status===s);r.style.display=show?'':'none';if(show)n++});document.getElementById('vehicle-count').textContent=n+' véhicule(s)'}function openDeleteVehicle(id,name){document.getElementById('delete-vehicle-id').value=id;document.getElementById('delete-vehicle-name').textContent=name;openModal('delete-vehicle-modal')}function openModal(id){document.getElementById(id).classList.add('show')}function closeModal(id){document.getElementById(id).classList.remove('show')}function toggleSidebar(){document.getElementById('dashboard-sidebar').classList.toggle('open');document.getElementById('mobile-overlay').classList.toggle('show')}setTimeout(()=>document.querySelector('.users-toast')?.remove(),4000);
</script></body></html>
