<?php
require_once __DIR__.'/../core/Model.php';
class EspaceEmploye extends Model
{
    public function getWorker(int$id):?array{$s=$this->db->prepare("SELECT t.*,f.nom fonction_nom,af.taux_remuneration FROM travailleurs t LEFT JOIN attribution_fonctions af ON af.travailleur_id=t.id AND af.statut='ACTIF' LEFT JOIN fonctions_travailleur f ON f.id=af.fonction_id WHERE t.id=? LIMIT 1");$s->execute([$id]);return$s->fetch()?:null;}
    public function getMovements(int$workerId):array
    {
        $sql="SELECT CONCAT('REC-',r.id) reference,'RECETTE' type_operation,r.date_recette date_operation,r.montant,r.devise,COALESCE(r.description,'Recette') libelle,r.cloturer,v.immatriculation FROM recettes r JOIN affectations_vehicule av ON av.id=r.affection_vehicule JOIN vehicules v ON v.id=av.vehicule_id WHERE EXISTS(SELECT 1 FROM affectations_vehicule own JOIN attribution_fonctions af ON af.id=own.attribution_id WHERE own.vehicule_id=av.vehicule_id AND own.statut_supprime=0 AND af.travailleur_id=?) UNION ALL SELECT CONCAT('DEP-',d.id),'DEPENSE',d.date_depense,d.montant,d.devise,d.libelle,d.cloturer,v.immatriculation FROM depenses d JOIN affectations_vehicule av ON av.id=d.affection_vehicule JOIN vehicules v ON v.id=av.vehicule_id WHERE EXISTS(SELECT 1 FROM affectations_vehicule own JOIN attribution_fonctions af ON af.id=own.attribution_id WHERE own.vehicule_id=av.vehicule_id AND own.statut_supprime=0 AND af.travailleur_id=?) ORDER BY date_operation DESC";$s=$this->db->prepare($sql);$s->execute([$workerId,$workerId]);return$s->fetchAll();
    }
    public function getEstimates(int$workerId):array
    {
        $sql="SELECT v.id,v.immatriculation,af.taux_remuneration,x.devise,x.recettes,x.depenses,GREATEST(0,x.recettes-x.depenses) base_remuneration,ROUND(GREATEST(0,x.recettes-x.depenses)*COALESCE(af.taux_remuneration,0)/100,2) estimation FROM affectations_vehicule own JOIN attribution_fonctions af ON af.id=own.attribution_id JOIN vehicules v ON v.id=own.vehicule_id JOIN(SELECT av.vehicule_id,z.devise,SUM(CASE WHEN z.type_operation='RECETTE' THEN z.montant ELSE 0 END) recettes,SUM(CASE WHEN z.type_operation='DEPENSE' THEN z.montant ELSE 0 END) depenses FROM(SELECT affection_vehicule,devise,montant,'RECETTE' type_operation FROM recettes WHERE cloturer=0 UNION ALL SELECT d.affection_vehicule,d.devise,d.montant,'DEPENSE' FROM depenses d JOIN categories_depenses c ON c.id=d.categorie_depense_id WHERE d.cloturer=0 AND c.type_depense='participatif')z JOIN affectations_vehicule av ON av.id=z.affection_vehicule GROUP BY av.vehicule_id,z.devise)x ON x.vehicule_id=own.vehicule_id WHERE af.travailleur_id=? AND af.statut='ACTIF' AND own.statut_supprime=0 AND own.date_debut<=CURDATE() AND(own.date_fin IS NULL OR own.date_fin>=CURDATE()) ORDER BY v.immatriculation,x.devise";$s=$this->db->prepare($sql);$s->execute([$workerId]);return$s->fetchAll();
    }
    public function getEarned(int$workerId):array{$out=['USD'=>0.0,'CDF'=>0.0];$s=$this->db->prepare("SELECT rt.devise,SUM(rt.montant) total FROM remunerations_travailleur rt JOIN attribution_fonctions af ON af.id=rt.attribution_id WHERE af.travailleur_id=? AND rt.actif=1 GROUP BY rt.devise");$s->execute([$workerId]);foreach($s->fetchAll()as$r)$out[$r['devise']]=(float)$r['total'];return$out;}
}
